"""empty message

Revision ID: 9a716283a5ea
Revises: 
Create Date: 2019-01-11 18:28:54.674900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a716283a5ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_media_announcement_charge', 'time_slot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_media_announcement_charge', sa.Column('time_slot', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
